### ISSUE TITLE
Add meta nodes

### ISSUE THREAD

**Issue by jkomoros** [jkomoros/adjacency-map#12]
Meta nodes are ones that are groupings of nodes that act as though it's the union of all inbound inputs and sums, and can contain leaf nodes or meta nodes.

**Comment by jkomoros** [comment]
- [x] Allow nodes to specify a metaNode
- [x] renderEdges needs to be changed so the RenderEdgeValue uses top level LayoutIDs, and map.renderEdges returns only those. But that requires combining edges in a group
  - [x] Each raw node passes out its bundled and unbundled render edges. Then each top level node goes through and fetches its inner render edges and takes all of the bundled ones and smooshes together with edgeCombiner, retargets any edges source/parent to the final layout id, and then removes any renderEdges whose source/target is the same thing (that is, they would have been internal edges within a group))
  - [x] No, just have renderEdges be a utility function that takes a source layoutID, a MapDefinition, and an array of nodes to combine. Then pop out the implementation of _calculateRenderEdges into that. When creating edgesByRef, it remaps the source/target of the edge into the LayoutID space, and drops any edges whose remapped source/target are the same (those are 'internal' edges). Then the rest of the calculation proceeds as before. And then renderEdges on AdjacencyMap just goes through only layoutNodes and asks each for its renderEdges.
- [x] Make it so edgeDefinitonHelper takes an array of nodes to start. (The nodes it should be passed in are only the nodes that have the current edge set)
- [ ] Do the implicit grouping
  - [x] Make sure there's a utility to take a graph and reverse its direction.
  - [x] Create an accumulateLabels method. It takes a graph of node-> child, a set of node->label, and a list of starter nodes. It returns a nodeID -> labelSet 
  - [x] Create a labelNodes. It calls accumulateLabels in both directions, and returns a map of nodeID -> {label, InboudnSet, outboundSet}. It takes graph and reverseGraph so it doesn't have to constantly reverse.
  - [x] Create an implyGroups. It takes a list of nodeID->group, nodeID->children, group-> group parent. It reutnrs a set of nodeID->impliedGroupLabel, and a new full set of groups (possibly eadding and twweaking some). First it creates the reverse node graph. Then it starts a loop. Inside it figures out hte rootLabel for each node by taking the groups list and reducing to the root labels, Then it calls labelNodes . Then it finds the nodes with the lowest overlap that don't yet have a group set, and creates a new group to unify those, and adds it to the final group set. Then it goes through the loop again. Now, test.
  - [x] Document the overally implyGroups procedure
- [ ] Allow a group to change its group in a scenario
- [ ] Allow modifying the group of a group live
- [ ] Rename edgeDefinitionHelper to something more generic. And split it so. it's possible to send the same cached arguments object to it so we don't recompute it 10x for each node's avlues 
- [x] It's possible a node that is not grouped but has a before node that is in a group and an after node that is grouped, and now it is effectively an 'internal' node even though it's not explicitly grouped. Basically if all of its inbound and outbound edges go to nodes that are in the same _rootLayoutID node. 
  - [x] This needs something like impliedGroup. and that has to be set via some explicit algorithm (it can't just be checking its inbound and outbound edges for all being the same _rootLayoutID, because it's possible there are two or more in the chain that are implicitly captured. 
  - [x] See the comment below for the algorithm for how to accomplish this
- [ ] Test
  - [ ] Setting a given group on a node in a scenario 
  - [ ] It's possible to unset a group on a node in a scenario
  - [ ] GroupDisplay overrides
- [x] Make it so edgeDefinitionHelper doesn't do node.parents, but edges.parents.unique. (The behavior is currently a parent for every type of edge, but it really only should be for that edge type). That removes one use of the singular node.
- [x] Document groupDisplay (on group and on map)
- [x] Actually wire through group display using the display properties
- [ ] Figure out a way to resolve the multiple nodes in edgeDefinitionHelper for result value (maybe that's an array of NodeValues in general?)
- [ ] Add a Test for an empty group nested underneath a non-empty node doesn't totally barf (as it did before 28fe5a0)
- [ ] `validateData` should validate no cycles in scenario extends and group nesting (and test that it does so)
- [x] There's a bug where a group that has no children is part of another group so the containing group calls the (empty) inner group during positioning and there's something undefined about it
- [x] Make it so edgeDefinitionHelper does a union of tags and selfTags if there are multiple parent nodes as the first argument (and disallow any other uses that don't have an obvious answer)
- [x] Make it so Group also has a renderEdges that passes all of its nodes to renderEdges
- [x] Make it so renderEdges uses an ID space of LayoutID (done at the top) and it culls out any source/parent edges that resolve to the same LayoutID (internal edges). map.renderEdges collects the renderEdges of all layoutNodes and renders them. For now just use the display value of the first node child. 
- [ ] Add tests that grouped layouts work correctly
- [x] TODO: do we call Node.group == undefined? because it only ever returns null or an object
- [x] Render out meta nodes
- [x] Document groups in README (including disableGroups)
- [x] Allow a metaNode to specify a metaNode.
- [ ] Allow toggling on and off rendering of subNodes in groups
- [ ] Allow changing whether groups are disabled live (similar to how scenarioName can be provided at constructor or as a setter)
- [x] Position inner circles by circle packing (https://github.com/d3/d3-hierarchy#packSiblings) 
- [x] Have the order of groups be based on topolgical sort of membership (so containing groups render behind things they contain; and then make sure nodes are always fully on top)
- [ ] Allow a groupPadding display property on nodes and groups which effectively add an extra amount to the radius for laying out (currently a constant based on number of peers)
- [x] Test having multi-nested layouts (on mac pro)
- [ ] The label for the top-level group shows rendered far too far to the left for some reason
- [ ] Fix bug where when you hover over a group, its text shows up beneath nodes to the left of it (we used to cheaply get the right behavior because nodes were ordered topographically so the text label for a thing to the right always rendered intrinsically above the other item)
- [ ] Allow changing the group of a node in the editable scenario.
- [x] Allow groupStrokeColor, groupColor, groupOpacity, groupStrokeWidth
- [x] Add property.groupCombiner, which is used before property.combiner for combining values.
- [x] Document groups in README (including disableGroups)
- [ ] disableGroups should be in the URL hash (as should editing, so that when you share a URL it goes to the same thing the person is seeing)
- [ ] Switch to an internal NodeDisplay POJO (similar to how RenderEdge is shaped). Reframe the internal getters as a layer of indirection around calculating it once but also have a getter to pass it through. Then do a test around e.g. "empty subgroups don't affect the display calculation of a group"
- [ ] Fix that if you're typing in a text control and use the arrow keys the scenarios will update
- [ ] If you hold down shift and shift scenarios the animation is 10x the length
- [ ] Add a way to unset a group in a later scenario
- [x] Allow meta node membership to be overridden in scenarios (implement a _scenarioChanged and invalidate caches on AdjacencyMapGroup)
- [ ]  Allow editing meta nodes live in UI (there's a difference between 'set the group to ''' and 'go back to the total default in this scenario'

**Comment by jkomoros** [comment]
The logic for impliedGroups is quite complex, especially if there are multiple groups. (I think there might be some cases where a new group that combines multiple peer groups might need to be created?)

The first step in the algorithm is to replace every node's group with the root group ID by walking all the way up the tree: the rootGroups are what we operate over.

Any nodes that are "contained" within a group, where it is upstream of group A and also group A can be reached downstream, are implicitly in group A.

This gets way harder with multple groups, because a given node might be captured by multiple groups. ... Maybe in those cases just barf and say it's not allowed?

Here's how it should work:

Create a map of each groupID to its final rootGroupID (by following up the group parent chain until a root). All of the calculations operate on rootGroupIDs.

Start at the root node, and flow through. For each node, keep track of which rootGroups we've seen upstream of it and continue processing each node in a BFS. 

Then, walk through the graph backwards, starting from any node that has only inbound edges, and adding all of their upstream edges to the starter BFS backlog. Then annotate each node with the rootGroups that are _downstream_ of it.

Then visit each node and compute its rank. Its rank is the number of pairs of rootGroups that are on both its inbound and outbound side, plus 1 if it has an explicit group set. Then visit the node with the highest rank. Create a new group that is the parent of all of the pairs + explicitly set Group (have a GroupDefinition.implied that is set to true). Then restart the dual-way BFS again (because now more groups will collapse into that new rootGroup we just created). If the highest rank is 1, then this no more BFS will be required. Go through each node and if there is not an explicit group already set, set it to the group that is paired in inbound + outbound.
